### ISSUE TITLE
Please explain plugin usefulness in the About

### ISSUE THREAD

**Issue by pcav** [CarlosCagna/DeactivateActiveLabels#1]
From the very short description it is unclear what is the new function introduced, compared to core functionality.

**Comment by CarlosCagna** [comment]
Hello, 
Thanks for your collaboration

Update the description for this
"This Plugin create one Button to on/off layer’s label and other Button to invert the on/off labels from all layers." 
what do you think?

**Comment by pcav** [comment]
Fine with me
